#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apt', 

  git: 'https://github.com/fnichol/chef-apt'

cookbook 'git', 

  git: 'https://github.com/fnichol/chef-git.git'

cookbook 'build-essential'

cookbook 'apache2',

  git: 'https://github.com/opscode-cookbooks/apache2'

cookbook 'rvm', 

  git: 'git://github.com/fnichol/chef-rvm.git', ref: 'v0.8.6'